### ISSUE TITLE
🚀 [feature] Api 응답 설정, 예외처리 설정

### ISSUE THREAD

**Issue by CYY1007** [Team-Shaka/Treehouse-SpringBoot#6]
# 🤖 기능 개요

Api 응답 양식을 결정하고 예외처리 처리를 설정합니다
이후 스프링 시큐리티 설정 작업을 합니다.

## ✅ Todo
- [x] Api 응답 dto 설계
- [x] 응답 enum 설계
- [x] 예외처리 핸들러 설계
