### ISSUE TITLE
🚀 [feature] 스웨거 세팅 및 Test API 구현, 명세 작성

### ISSUE THREAD

**Issue by HyoBN** [Team-Shaka/Treehouse-SpringBoot#8]
# 🤖 기능 개요
스웨거 세팅 및 Test 용 Get, Post API 구현, 명세 작성

## ✅ Todo
- [ ] 스웨거 도입 및 세팅
- [ ] Test 용 Get, Post API 구현
- [ ] API 명세 작성
