### ISSUE TITLE
🚀 [feature] 알림 관련 기능 추가

### ISSUE THREAD

**Issue by koojun99** [Team-Shaka/Treehouse-SpringBoot#84]
# 🤖 기능 개요

알림 관련 기능 추가
## ✅ Todo
- [x] 반응(Reaction) 관련 알림의 경우 이모지값도 보여주기
- [x] 특정 알림을 타고 페이지로 이동한 경우 `isChecked` 필드 true로 변경
- [x] NotificationType(댓글,답글, 감정표현, 초대)에 해당하는 로직 실행 시, 알림 객체도 생성하도록 수정
